// Code generated by command: go run asm.go -out svb.s -stubs stub.go. DO NOT EDIT.

package svb

// Shuffle 32 bits integer using XMM register, AVX
func Shuffle128(shuffle []byte, data []byte, out []uint32)

// Shuffle 32 bits integer using YMM register, AVX2
func Shuffle256(masks []byte, data []byte, out []uint32) byte

// Shuffle 32 bits integer using ZMM register, AVX512
func Shuffle512(masks []byte, data []byte, out []uint32) byte
